In [16]:
L = list(range(10))

In [13]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
[type(a) for a in L]

[int, int, int, int, int, int, int, int, int, int]

In [20]:
import array
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
import numpy as np
np.array(L)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.array([range(i, i + 5) for i in [4, 7, 9]])

array([[ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11],
       [ 9, 10, 11, 12, 13]])

In [32]:
np.zeros(10, dtype=int)
np.ones((4, 6), dtype=float)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [33]:
np.full((4,7), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [34]:
np.linspace(0,6,10)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [36]:
np.random.random((3,2))

array([[0.64810969, 0.68268537],
       [0.22245937, 0.54184145],
       [0.31802545, 0.88067365]])

In [55]:
np.random.normal(4,4, (10,8))

array([[ 4.1199922 ,  0.0793702 ,  2.39697529,  7.53893355, -3.87697978,
        10.00522519,  5.72460095,  5.02051471],
       [ 8.47326477,  1.49110948,  2.43184071, -3.43584954,  2.60266153,
         9.79365982,  6.53497996, -1.17041743],
       [ 8.10788223,  6.92119534,  7.06780509,  2.73912952,  9.14312563,
         1.00743714,  7.40727124,  5.05708778],
       [ 5.44214165,  6.01043736, 10.28728782,  6.15149767,  9.0255229 ,
         6.91059204,  5.10267154,  7.51424491],
       [ 0.95200064,  5.93692969,  9.26081678,  1.01386116,  1.20626735,
         3.87951475, -0.42251414,  2.38843823],
       [ 0.96019882,  2.88592867,  6.34099363,  2.47665883,  3.86833431,
         2.15122685,  5.54534003,  5.81180309],
       [ 7.23754017,  4.42180358,  3.84939018, -4.84361984,  1.81028276,
         4.23583527,  3.41471459,  8.26697171],
       [ 6.96068763,  7.70455811,  8.97650839, -1.2617578 ,  3.52879957,
         5.4601284 , -4.28981867,  3.97784417],
       [11.11335707,  4.03631048

In [56]:
!pip3 install torch
!pip3 install hyperopt
!pip3 install googledrivedownloader
!pip3 install tqdm

    100% |████████████████████████████████| 676.9MB 2.4kB/s eta 0:00:01    24% |███████▊                        | 164.1MB 15.5MB/s eta 0:00:34    35% |███████████▌                    | 242.8MB 8.9MB/s eta 0:00:49 |██████████████████              | 380.0MB 12.3MB/s eta 0:00:25�█████▉            | 418.6MB 12.8MB/s eta 0:00:21�██████            | 424.4MB 14.4MB/s eta 0:00:18███         | 486.0MB 10.4MB/s eta 0:00:19MB 16.9MB/s eta 0:00:09    88% |████████████████████████████▍   | 599.3MB 30.6MB/s eta 0:00:03
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1437aacc88>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/hyperopt/
    100% |████████████████████████████████| 122kB 6.0MB/s ta 0:00:01
    100% |████████████████████████████████| 1.8MB 872kB/s eta 0:00:01
    100% |████████████████████████████████

In [57]:
# To download our dataset
from google_drive_downloader import GoogleDriveDownloader

# Visualization
from tqdm import tqdm_notebook as tqdm
import matplotlib.pyplot as plt

# Data manipulation
import pandas as pd
import numpy as np

# Deep learning
import torch
from torch.optim import Adam
import torch.nn as nn
import torch.nn.functional as F

# Preprocessing and scoring
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, log_loss, precision_recall_curve
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
#from sklearn.utils.fixes import 

# Hyperparameter tuning
from hyperopt import space_eval
from hyperopt import fmin, hp, tpe

ModuleNotFoundError: No module named 'sklearn'

In [58]:
from google_drive_downloader import GoogleDriveDownloader

In [59]:
CREDIT_ID = '1c0EKXaupL9Y_ttxKm0ujhnZ3QSYXNO9f'
GoogleDriveDownloader.download_file_from_google_drive(file_id=CREDIT_ID,
                                                      dest_path='./credit_data',
                                                      unzip=True)

Unzipping...Done.


In [60]:
!pwd

/media/mbaye/DATA/mescours/datascience/dev/datasciencecourses
